### ISSUE TITLE
Issue while updating validator or setting up afresh - may or may not be related to Ubuntu 24.04

### ISSUE THREAD

**Issue by RaMurd-Crypto** [rhmaxdotorg/pulsechain-validator#40]
History: My validators originally setup using these script on Ubutu 22.04 have working flawlessly for over an year. Recently I got a notification to upgrade to the latest Ubutu 24.04 LTS. I upgraded after getting confirmation for other users in TG PulseDev that it works on 24.04. After I upgraded, it did work fine for two days.
Yesterday night I had a power failure, since then my validator would not work (waited over 10 hours). On investigating, found that beacon database may have corrupted.

- I first attempted to update the validators using the update script, I got a error (compilation error)
error[E0282]: type annotations needed for `Box<_>`
  --> /home/node/.cargo/registry/src/index.crates.io-6f17d22bba15001f/time-0.3.34/sr /format_description/parse/mod.rs:83:9

I assumed that it might work if I did a fresh setup, so I reset the validators using the reset script and tried to rerun the setup script, it ended up having the exact same compilation error for the crate `time`

I researched on the internet and tried manually installing the latest rustup and then the latest stable toolchain, it did not change the outcome.

At this time, I am stuck, any help would be appreciated.

I am on Ubuntu 24.04
and Rust/Cargo version is 1.81

I am willing to switch to the dockerized approach, if anybody has instructions on how to migrate my staking deposits over.

**Comment by Sipheren** [comment]
I think you are probably having the same issue I was, its to do with the cargo update. You'll need to add some lines to the setup script, though, one of my nodes I had to run setup, let it fail, then manually nav to the rust location and do the cargo update, after that the setup ran fine. Hopefully that helps.

Original Thread:
https://github.com/rhmaxdotorg/pulsechain-validator/issues/38

**Comment by RaMurd-Crypto** [comment]
Thank you for a quick reply. I will give it a try.

**Comment by RaMurd-Crypto** [comment]
I was able to overcome this issue by using older version of rust toolchain.
Modified the script 
Changed this line
`sudo -u $NODE_USER bash -c "cd \$HOME && curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y"`
to
`sudo -u $NODE_USER bash -c "cd \$HOME && curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs/ | sh -s -- --default-toolchain=1.79.0 -y"`

was able to successfully build lighthouse.

**Comment by RaMurd-Crypto** [comment]
I was able to overcome this issue by using older version of rust toolchain.
Modified the script
Changed this line
sudo -u $NODE_USER bash -c "cd \$HOME && curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y"
to
sudo -u $NODE_USER bash -c "cd \$HOME && curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs/ | sh -s -- --default-toolchain=1.79.0 -y"
